export type Review = {
  slug: string;
  category: string;
  title: string;
  place: string;
  score: string;
  image: string;
  alt: string;
  summary: string;
  saw: string[];
};

export const categories = ["Restaurants", "Schools", "Universities", "Hospitals", "Hotels"];

export function categorySlug(category: string) {
  return category.toLowerCase();
}

export const reviews: Review[] = [
  {
    slug: "fire-platter",
    category: "Restaurants",
    title: "Liido Grill",
    place: "The table",
    score: "8/10",
    image: "/photos/grill-platter.jpg",
    alt: "Grilled skewers, charred pepper, eggplant, potatoes, and bowls of sauce",
    summary: "Skewers, a charred pepper, eggplant, potatoes, and several sauces on one board.",
    saw: ["Chicken and meat on metal skewers.", "A blistered pepper and a dark eggplant.", "Small bowls of red, white, and yellow sauce."],
  },
  {
    slug: "glazed-ribs",
    category: "Restaurants",
    title: "Jubba Table",
    place: "The table",
    score: "8/10",
    image: "/photos/ribs.jpg",
    alt: "Glazed ribs with tomato slices, pickles, and fries",
    summary: "A long rack of glazed ribs, with tomato, pickles, and a paper cone of fries.",
    saw: ["The ribs are dark and cut into sections.", "Tomato slices sit on the left.", "Pickles and fries come beside the meat."],
  },
  {
    slug: "dining-room",
    category: "Restaurants",
    title: "Gold Room",
    place: "The room",
    score: "9/10",
    image: "/photos/dining-room.jpg",
    alt: "A dining room with black chairs, wood tables, and gold screens",
    summary: "Black chairs, pale wood tables, and gold screens. The room is already set.",
    saw: ["Glasses are on the tables.", "Gold slat screens divide the room.", "Daylight comes from the tall windows."],
  },
  {
    slug: "house-bread",
    category: "Restaurants",
    title: "Daljir Bakery",
    place: "The bread board",
    score: "7/10",
    image: "/photos/bread.jpg",
    alt: "Three round seeded loaves and a wheat stalk",
    summary: "Three round loaves. One is covered in sunflower seeds, one in mixed seeds, one in flour.",
    saw: ["The loaves are round, not sliced.", "Seeds cover two of the crusts.", "A wheat stalk lies across the front loaf."],
  },
  {
    slug: "empty-classroom",
    category: "Schools",
    title: "Najma School",
    place: "The classroom",
    score: "8/10",
    image: "/photos/school-class.jpg",
    alt: "Rows of school desks facing a green chalkboard",
    summary: "Rows of green-topped desks face a green board, a wooden desk, and a wall map.",
    saw: ["Desks are paired and empty.", "The board is clean.", "A map hangs on the right wall."],
  },
  {
    slug: "lesson",
    category: "Schools",
    title: "Al-Huda School",
    place: "The classroom",
    score: "8/10",
    image: "/photos/school-yard.jpg",
    alt: "Students seated at desks while a teacher stands at the board",
    summary: "Students sit at shared desks. A teacher stands at the front beside a bright screen.",
    saw: ["Backpacks hang on the chairs.", "The walls are covered with class papers.", "The teacher faces the class."],
  },
  {
    slug: "first-desk",
    category: "Schools",
    title: "Imam Shafici School",
    place: "The desk",
    score: "7/10",
    image: "/photos/school-desk.jpg",
    alt: "Books, an apple, colored pencils, and ABC blocks",
    summary: "A stack of books, one red apple, colored pencils, and blocks marked A, B, and C.",
    saw: ["The apple sits on the top book.", "The pencils are loose on the wood.", "The blocks are stacked C, B, A."],
  },
  {
    slug: "drawing-table",
    category: "Schools",
    title: "Al-Nur School",
    place: "The classroom",
    score: "8/10",
    image: "/photos/school-hall.jpg",
    alt: "Children drawing at a classroom table",
    summary: "Children lean over paper and open workbooks at a long table.",
    saw: ["A boy in a green shirt draws in the foreground.", "Open pages show numbered drawings.", "Boxes and a window sit behind the table."],
  },
  {
    slug: "college-front",
    category: "Universities",
    title: "Somali National University",
    place: "The campus",
    score: "9/10",
    image: "/photos/uni-hall.jpg",
    alt: "A large brick and stone college building behind a green lawn",
    summary: "A wide brick building with a pale stone center, many windows, and a lawn in front.",
    saw: ["The center has tall columns and a small tower.", "Trees line the front.", "The lawn is empty."],
  },
  {
    slug: "graduation-lawn",
    category: "Universities",
    title: "SIMAD University",
    place: "The lawn",
    score: "8/10",
    image: "/photos/uni-campus.jpg",
    alt: "Graduates in black gowns throwing caps on a lawn",
    summary: "Graduates in black gowns and yellow hoods throw their caps above a dry lawn.",
    saw: ["Six people stand with their backs to the camera.", "Caps are in the air.", "A city skyline is behind them."],
  },
  {
    slug: "university-aisle",
    category: "Universities",
    title: "Mogadishu University",
    place: "The library",
    score: "9/10",
    image: "/photos/library.jpg",
    alt: "A long library aisle with shelves and hanging bulbs",
    summary: "One long wall of books, and a line of bare bulbs above the aisle.",
    saw: ["The shelves are full.", "The bulbs hang on black cords.", "The far end of the aisle is brighter."],
  },
  {
    slug: "university-stacks",
    category: "Universities",
    title: "Plasma University",
    place: "The library",
    score: "8/10",
    image: "/photos/uni-shelves.jpg",
    alt: "A wall of wooden shelves packed with books",
    summary: "Wooden shelves run from the floor upward and are packed with books.",
    saw: ["Light falls across the lower shelves.", "Some books stand, some lean.", "The top rows are in shadow."],
  },
  {
    slug: "clinic-desk",
    category: "Hospitals",
    title: "Shaafi Hospital",
    place: "The entrance",
    score: "8/10",
    image: "/photos/hospital-corridor.jpg",
    alt: "A curved clinic reception desk with a blue floor sign",
    summary: "A curved glass desk, a blue tile wall, and a sign for the first floor.",
    saw: ["The sign lists lifts, a bathroom, and therapy rooms.", "A lift door is on the left.", "The desk glass is closed."],
  },
  {
    slug: "operating-room",
    category: "Hospitals",
    title: "Digfeer Hospital",
    place: "The theatre",
    score: "9/10",
    image: "/photos/hospital-bed.jpg",
    alt: "An empty operating room with lights and a surgical table",
    summary: "A black operating table sits under round surgical lights. Screens line the wall.",
    saw: ["The table is empty.", "Two large lights hang from the ceiling.", "Monitors are on, and the room is bright."],
  },
  {
    slug: "hospital-entrance",
    category: "Hospitals",
    title: "Banadir Hospital",
    place: "The drive",
    score: "8/10",
    image: "/photos/hospital-front.jpg",
    alt: "A brick hospital with a wide canopy over the entrance",
    summary: "A brick hospital with a long metal canopy over the front doors.",
    saw: ["Cars wait under the canopy.", "The driveway curves in from the street.", "Rows of windows cover the upper floors."],
  },
  {
    slug: "ward",
    category: "Hospitals",
    title: "Medina Hospital",
    place: "The ward",
    score: "8/10",
    image: "/photos/hospital-desk.jpg",
    alt: "Hospital beds with blue covers and pink curtains",
    summary: "Metal beds with blue covers stand in a row. Pink curtains hang between them.",
    saw: ["The beds are made and empty.", "Rails and wheels are visible.", "Long lights run above the row."],
  },
  {
    slug: "pool-deck",
    category: "Hotels",
    title: "Jazeera Hotel",
    place: "The deck",
    score: "8/10",
    image: "/photos/hotel-lobby.jpg",
    alt: "A hotel pool, lounge chairs, and a wooden building",
    summary: "A curved pool, white lounge chairs, and a two-storey wooden building.",
    saw: ["A palm stands on the deck.", "Chairs face the water.", "The building has a broad brown roof."],
  },
  {
    slug: "white-courtyard",
    category: "Hotels",
    title: "SYL Hotel",
    place: "The pool",
    score: "9/10",
    image: "/photos/hotel-room.jpg",
    alt: "A hotel pool courtyard with palms and white buildings",
    summary: "White buildings, tall palms, and a still pool under a pink sky.",
    saw: ["Closed umbrellas stand by the water.", "Low daybeds line the pool.", "Warm lights are on in the rooms."],
  },
  {
    slug: "guest-room",
    category: "Hotels",
    title: "Peace Hotel",
    place: "The room",
    score: "9/10",
    image: "/photos/hotel-bed.jpg",
    alt: "A hotel bedroom with a wooden bed and a garden window",
    summary: "A low wooden bed, teal cushions, and a window onto a planted courtyard.",
    saw: ["A white robe hangs by the desk.", "Lamps sit on both sides of the bed.", "The garden is visible through the glass."],
  },
  {
    slug: "evening-pool",
    category: "Hotels",
    title: "Sahafi Hotel",
    place: "The entrance",
    score: "9/10",
    image: "/photos/hotel-pool.jpg",
    alt: "A lit hotel pool in front of an open evening lobby",
    summary: "A lit pool sits in front of an open lobby. The sky is deep blue.",
    saw: ["The water reflects the lobby lights.", "Chairs and tables are inside the open hall.", "A ladder is at the right edge of the pool."],
  },
];
